SET TIME ZONE 'UTC';

DROP SCHEMA public CASCADE;

CREATE SCHEMA alpha;

-- CREATE ADMIN ROLE
CREATE ROLE admin WITH LOGIN SUPERUSER CREATEDB CREATEROLE REPLICATION NOINHERIT PASSWORD 'password';
GRANT ALL PRIVILEGES ON DATABASE depotaf to admin;
ALTER ROLE admin SET search_path = alpha;

-- ALTER READ_WRITE USER ROLE
GRANT ALL PRIVILEGES ON DATABASE depotaf to postgres;
GRANT CONNECT ON DATABASE depotaf TO postgres;
GRANT USAGE ON SCHEMA alpha TO postgres;
GRANT CREATE ON SCHEMA alpha TO postgres;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA alpha TO postgres;
GRANT USAGE, SELECT, UPDATE ON ALL SEQUENCES IN SCHEMA alpha TO postgres;
GRANT EXECUTE ON ALL FUNCTIONS IN SCHEMA alpha TO postgres;
ALTER ROLE postgres SET search_path TO alpha, public; 
ALTER ROLE postgres WITH NOINHERIT;
