version: '3'
services:
    airflow-app:
        container_name: airflow-app
        build:
            context: .
            dockerfile: ./docker/airflow/Dockerfile
        image: airflow_depot:latest
        restart: always
        ports:
            - '8080:8080'
        env_file:
            - './docker/airflow/airflow.env'
        depends_on:
            - airflowdb
            - postgres
        volumes:
            - './dags:/usr/local/airflow/dags'
            - './depot:/usr/local/airflow/depot'
            - './processed:/usr/local/airflow/processed'
    postgres:
        container_name: postgres
        build:
            context: .
            dockerfile: ./docker/postgres/Dockerfile
        restart: always
        image: postgres_depot:latest
        env_file:
            - './docker/postgres/postgres.env'
        ports:
            - '5432:5432'
        volumes:
            - './pgdata:/var/lib/postgresql/data'
    airflowdb:
        container_name: airflowdb
        build:
            context: .
            dockerfile: ./docker/postgres_airflow/Dockerfile
        image: airflowdb:latest
        restart: always
        env_file:
            - './docker/postgres_airflow/postgres.env'
        ports:
            - '5433:5432'
        volumes:
            - './pgdata_airflow:/var/lib/postgresql/data'
volumes:
    pgdata:
        external: true
